# Generated by Django 3.1.1 on 2020-10-12 11:41

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address_de',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=250)),
                ('hnr', models.CharField(max_length=10)),
                ('postcod', models.CharField(max_length=4)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IndexSlider_de',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greetings', models.CharField(max_length=50)),
                ('title_bold', models.CharField(max_length=50)),
                ('slider_image', models.ImageField(upload_to='index/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lang_flag', models.ImageField(blank=True, null=True, upload_to='myresume/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Navigation_brand_de',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_brand', models.CharField(max_length=50)),
                ('nav_image', models.ImageField(upload_to='index/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSection_de',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='myresume/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Berufslaufbahn', 'Berufslaufbahn'), ('Ausbildung', 'Ausbildung'), ('Zertifikate', 'Zertifikate'), ('Sprachen', 'Sprachen')], max_length=25, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('institution_url', models.URLField(blank=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('company_url', models.URLField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(default='Austria', max_length=2, null=True)),
                ('from_year', models.DateField(blank=True, default=None, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('to_year', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('fa_url', models.CharField(max_length=50)),
            ],
        ),
    ]
