# Generated by Django 3.1.1 on 2020-10-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_de', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languages',
            new_name='Languages_de',
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='Project_de',
        ),
        migrations.RenameModel(
            old_name='SectionEntries',
            new_name='SectionEntries_de',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Services_de',
        ),
    ]
