# Generated by Django 3.1.1 on 2020-09-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greetings', models.CharField(max_length=50)),
                ('title_bold', models.CharField(max_length=50)),
                ('slider_image', models.ImageField(upload_to='index/images/')),
            ],
        ),
    ]
