# Generated by Django 3.1.1 on 2020-09-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=250)),
                ('hnr', models.CharField(max_length=10)),
                ('postcod', models.CharField(max_length=4)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Navigation_brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_brand', models.CharField(max_length=50)),
                ('nav_image', models.ImageField(upload_to='index/images/')),
            ],
        ),
    ]
