# Generated by Django 3.1.1 on 2020-09-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_sectionentries_company_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionentries',
            name='institution_url',
            field=models.URLField(blank=True),
        ),
    ]
