# Generated by Django 3.1.1 on 2020-09-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_sectionentries_institution_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumesection',
            old_name='title',
            new_name='section',
        ),
    ]
