# Generated by Django 3.1.1 on 2020-09-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20200910_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionentries',
            name='category_new',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
