# Generated by Django 3.1.1 on 2020-09-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_remove_sectionentries_category_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionentries',
            name='category',
            field=models.CharField(blank=True, choices=[('ex', 'Experience'), ('ed', 'Education'), ('ce', 'Certifications'), ('la', 'Languages')], max_length=25, null=True),
        ),
    ]
