# Generated by Django 3.1.1 on 2020-09-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20200911_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionentries',
            name='section',
        ),
    ]
