# Generated by Django 3.1.1 on 2020-09-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_remove_sectionentries_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lang_flag', models.ImageField(blank=True, null=True, upload_to='myresume/images/')),
            ],
        ),
    ]
