# Generated by Django 3.1.1 on 2020-10-08 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrivals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Chunri', 'Chunri'), ('Dresses', 'Dresses'), ('Jewellery', 'Jewellery')], max_length=25)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('rating', models.IntegerField(default=5)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(100000)])),
            ],
        ),
    ]
