# Generated by Django 3.1.1 on 2020-10-13 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chotihatti', '0004_auto_20201013_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrivals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Chunri', 'Chunri'), ('Dresses', 'Dresses'), ('Jewellery', 'Jewellery')], max_length=25)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('rating', models.IntegerField(default=5)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(100000)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='chotihatti/images/')),
            ],
        ),
    ]
