# Generated by Django 3.1.1 on 2020-10-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chotihatti', '0005_newarrivals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunris',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chotihatti/images/'),
        ),
    ]
